#! /usr/bin/env sh

is_device_set=false
is_online=false

# Resolve arguments
while getopts ":d:" opt; do
  case $opt in
    d)
      is_device_set=true
      device_name=$OPTARG
      ;;
    :)
	  echo ""
      echo "Option -$OPTARG requires device name as an argument"
      echo "Check available devices using 'adb devices'" >&2
      exit 1
      ;;
  esac
done

while getopts ":o" opt; do
  case $opt in
    o)
      is_online=true
      ;;
    :)
      ;;
  esac
done



# Gradle build and install
if [ $is_online = true ] ;
	then ./gradlew installDebug -PminSdkDebug=23;
else
	./gradlew installDebug -PminSdkDebug=23 --offline;
fi

if [ $is_device_set = true ] ; 
	then adb -s $device_name shell am start -n com.stylabs.styfi.app.debug/com.stylabs.styfi.app.SplashActivity;
else 
	adb shell am start -n com.stylabs.styfi.app.debug/com.stylabs.styfi.app.SplashActivity;
fi  

